project_id = "ebbmofwdghxsudvbakql"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.financial-ai-advisor]
verify_jwt = true